In [2]:
import pandas as pd

In [8]:
# read mw/study-study_id-ST-named_metabolites.json into a dataframe
df = pd.read_json('data/mw/study-study_id-ST-named_metabolites.json')

In [9]:
df.head()

,1,2,3,4,5,6,7,8,9,10,...,2878,2879,2880,2881,2882,2883,2884,2885,2886,2887
study_id,ST000001,ST000002,ST000003,ST000004,ST000004,ST000004,ST000004,ST000004,ST000004,ST000004,...,ST002863,ST002864,ST002865,ST002867,ST002869,ST002869,ST002870,ST002872,ST002915,ST002916
study_title,Fatb Induction Experiment (FatBIE),Intestinal Samples II pre/post transplantation,Metabolomic analysis of mouse embryonic fibrob...,Lipidomics studies on NIDDK / NIST human plasm...,Lipidomics studies on NIDDK / NIST human plasm...,Lipidomics studies on NIDDK / NIST human plasm...,Lipidomics studies on NIDDK / NIST human plasm...,Lipidomics studies on NIDDK / NIST human plasm...,Lipidomics studies on NIDDK / NIST human plasm...,Lipidomics studies on NIDDK / NIST human plasm...,...,Metabolic profiling and glucose tracing in nai...,"Metabolic profiling, glucose tracing and gluta...","Metabolic profiling, glucose tracing and gluta...",Root VOCs of Arabidopsis thaliana and its mutants,Identifying Biodegradation Pathways of Cetrimo...,Identifying Biodegradation Pathways of Cetrimo...,A carbon-nitrogen negative feedback loop under...,Comparative multi-omics analyses of cardiac mi...,MoTrPAC: Endurance exercise training study in ...,MoTrPAC: Endurance exercise training study in ...
institute,"University of California, Davis","University of California, Davis","University of California, Davis",LIPID MAPS,LIPID MAPS,LIPID MAPS,LIPID MAPS,LIPID MAPS,LIPID MAPS,LIPID MAPS,...,"University of California, Los Angeles","University of California, Los Angeles","University of California, Los Angeles",National University of Singapore,Arizona State University,Arizona State University,King Abdullah University of Science and Techno...,Weill Cornell Medicine,University of Michigan,University of Michigan
analysis_id,AN000001,AN000002,AN000003,AN000004,AN000005,AN000006,AN000007,AN000008,AN000009,AN000010,...,AN004695,AN004696,AN004697,AN004700,AN004702,AN004703,AN004704,AN004708,AN004785,AN004786
analysis_type,MS,MS,MS,MS,MS,MS,MS,MS,MS,MS,...,MS,MS,MS,MS,MS,MS,MS,MS,MS,MS

In [10]:
#transpose the dataframe
df = df.transpose()

In [13]:
df['study_id'].unique().size

1907

In [17]:
df[df['analysis_type'] == 'NMR']['study_id'].unique().size

111

In [19]:
df.head()

,study_id,study_title,institute,analysis_id,analysis_type,units,num_metabolites,details,species
1,ST000001,Fatb Induction Experiment (FatBIE),"University of California, Davis",AN000001,MS,Peak height,102,GCMS positive ion mode,Arabidopsis thaliana
2,ST000002,Intestinal Samples II pre/post transplantation,"University of California, Davis",AN000002,MS,Peak height,142,GCMS positive ion mode,Homo sapiens
3,ST000003,Metabolomic analysis of mouse embryonic fibrob...,"University of California, Davis",AN000003,MS,Peak height,51,LC/MS positive ion mode,Mus musculus
4,ST000004,Lipidomics studies on NIDDK / NIST human plasm...,LIPID MAPS,AN000004,MS,pmol/ml,107,Fatty acid/eicosanoid MS quantitative analysis...,Homo sapiens
5,ST000004,Lipidomics studies on NIDDK / NIST human plasm...,LIPID MAPS,AN000005,MS,pmol/ml,160,Phospholipid MS quantitative analysis with odd...,Homo sapiens

In [20]:
df[df['analysis_type'] == 'MS']

,study_id,study_title,institute,analysis_id,analysis_type,units,num_metabolites,details,species
1,ST000001,Fatb Induction Experiment (FatBIE),"University of California, Davis",AN000001,MS,Peak height,102,GCMS positive ion mode,Arabidopsis thaliana
2,ST000002,Intestinal Samples II pre/post transplantation,"University of California, Davis",AN000002,MS,Peak height,142,GCMS positive ion mode,Homo sapiens
3,ST000003,Metabolomic analysis of mouse embryonic fibrob...,"University of California, Davis",AN000003,MS,Peak height,51,LC/MS positive ion mode,Mus musculus
4,ST000004,Lipidomics studies on NIDDK / NIST human plasm...,LIPID MAPS,AN000004,MS,pmol/ml,107,Fatty acid/eicosanoid MS quantitative analysis...,Homo sapiens
5,ST000004,Lipidomics studies on NIDDK / NIST human plasm...,LIPID MAPS,AN000005,MS,pmol/ml,160,Phospholipid MS quantitative analysis with odd...,Homo sapiens
...,...,...,...,...,...,...,...,...,...
2883,ST002869,Identifying Biodegradation Pathways of Cetrimo...,Arizona State University,AN004703,MS,counts per second,132,HILIC NEGATIVE ION MODE,
2884,ST002870,A carbon-nitrogen negative feedback loop under...,King Abdullah University of Science and Techno...,AN004704,MS,peak area,6,HILIC POSITIVE ION MODE,Multiple Cnidarian species: Exaiptasia diaphan...
2885,ST002872,Comparative multi-omics analyses of cardiac mi...,Weill Cornell Medicine,AN004708,MS,Peak intensity,167,HILIC POSITIVE ION MODE,Mus musculus
2886,ST002915,MoTrPAC: Endurance exercise training study in ...,University of Michigan,AN004785,MS,peak area,160,Reversed phase NEGATIVE ION MODE,Rattus norvegicus
2887,ST002916,MoTrPAC: Endurance exercise training study in ...,University of Michigan,AN004786,MS,peak area,160,Reversed phase NEGATIVE ION MODE,Rattus norvegicus

In [21]:
import requests

In [22]:
for studyid in df[df['analysis_type'] == 'MS']['study_id'].unique():
    with open(studyid + '_metabolites.json', 'w') as f:
        f.write(requests.get('https://www.metabolomicsworkbench.org/rest/study/study_id/' + studyid + '/metabolites').text)

In [23]:
import glob
stmetabolites = glob.glob('data/mw/ST_metabolites/ST*_metabolites.json')

In [25]:
dfs = []
for jsonpath in stmetabolites:
    df = pd.read_json(jsonpath)
    dfs.append(df)

ValueError: If using all scalar values, you must pass an index

In [26]:
# read a json file into a dictionary
import json
with open(stmetabolites[3]) as f:
    data = json.load(f)

In [27]:
data.keys()

dict_keys(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46', '47', '48', '49', '50', '51', '52', '53', '54', '55', '56', '57', '58', '59', '60', '61', '62', '63', '64', '65', '66', '67', '68', '69', '70', '71', '72', '73', '74', '75', '76', '77', '78', '79', '80', '81', '82', '83', '84', '85', '86', '87', '88', '89', '90', '91', '92', '93', '94', '95', '96', '97', '98', '99', '100', '101', '102', '103', '104', '105', '106', '107', '108', '109', '110', '111', '112', '113', '114', '115', '116', '117', '118', '119', '120', '121', '122', '123', '124', '125', '126', '127', '128', '129', '130', '131', '132', '133', '134', '135', '136', '137', '138', '139', '140', '141', '142', '143', '144', '145', '146', '147', '148', '149', '150', '151', '152', '153', '154', '155', '156', '157', '158', '159', '160', '161', '162', '163', '164', '165', '166', '167', '168', '169', '170', '171', '172', '173', '174', '175', '176', '177', '178', '179', '180', '181', '182', '183', '184', '185', '186', '187', '188', '189', '190', '191', '192', '193', '194', '195', '196', '197', '198', '199', '200', '201', '202', '203', '204', '205', '206', '207', '208', '209', '210', '211', '212', '213', '214', '215', '216', '217', '218', '219', '220', '221', '222', '223', '224', '225', '226', '227', '228', '229', '230', '231', '232', '233', '234', '235', '236', '237', '238', '239', '240', '241', '242', '243', '244', '245', '246', '247', '248', '249', '250', '251', '252', '253', '254', '255', '256', '257', '258', '259', '260', '261', '262', '263', '264', '265', '266', '267', '268', '269', '270', '271', '272', '273', '274', '275', '276', '277', '278', '279', '280', '281', '282', '283', '284', '285', '286', '287', '288', '289', '290', '291', '292', '293', '294', '295', '296', '297', '298', '299', '300', '301', '302', '303', '304', '305', '306', '307', '308', '309', '310', '311', '312', '313', '314', '315', '316', '317', '318', '319', '320', '321', '322', '323', '324', '325', '326', '327', '328', '329', '330', '331', '332', '333', '334', '335', '336', '337', '338', '339', '340', '341', '342', '343', '344', '345', '346', '347', '348', '349', '350', '351', '352', '353', '354', '355', '356', '357', '358', '359', '360', '361', '362', '363', '364', '365', '366', '367', '368', '369', '370', '371', '372', '373', '374', '375', '376', '377', '378', '379', '380', '381', '382', '383', '384', '385', '386', '387', '388', '389', '390', '391', '392', '393', '394', '395', '396', '397', '398', '399', '400', '401', '402', '403', '404', '405', '406', '407', '408', '409', '410', '411', '412', '413', '414', '415', '416', '417', '418', '419', '420', '421', '422', '423', '424', '425', '426', '427', '428', '429', '430', '431', '432', '433', '434', '435', '436', '437', '438', '439', '440', '441', '442', '443', '444', '445', '446', '447', '448', '449', '450', '451', '452', '453', '454', '455', '456', '457', '458', '459', '460', '461', '462', '463', '464', '465', '466', '467', '468', '469', '470', '471', '472', '473', '474', '475', '476', '477', '478', '479', '480', '481', '482', '483', '484', '485', '486', '487', '488', '489', '490', '491', '492', '493', '494', '495', '496', '497', '498', '499', '500', '501', '502', '503', '504', '505', '506', '507', '508', '509', '510', '511', '512', '513', '514', '515', '516', '517', '518', '519', '520', '521', '522', '523', '524', '525', '526', '527', '528', '529', '530', '531', '532', '533', '534', '535', '536', '537', '538', '539', '540'])

In [28]:
data['100']

{'study_id': 'ST000004',
 'analysis_id': 'AN000004',
 'analysis_summary': 'Fatty acid/eicosanoid MS quantitative analysis with deuterated standards',
 'metabolite_name': 'PGF2alpha',
 'refmet_name': 'PGF2alpha'}

In [47]:
import json
# write dictionary values to a file as a tab-delimited table
with open('ST_metabolites_all.tsv', 'w') as f:
    for jsonpath in stmetabolites:
        with open(jsonpath) as f2:
            data = json.load(f2)
            if type(data) is list:
                pass
            else:
                #print(jsonpath)
                keys = data.keys()
                if 'refmet_name' in keys:
                    f.write(data['study_id'] + '\t')
                    f.write(data['analysis_id'] + '\t')
                    f.write(data['analysis_summary'] + '\t')
                    f.write(data['refmet_name'] + '\n')
                else:
                    for key in keys:
                        metabolite = data[key]
                        if metabolite['refmet_name'] != "":
                            f.write(metabolite['study_id'] + '\t')
                            f.write(metabolite['analysis_id'] + '\t')
                            f.write(metabolite['analysis_summary'] + '\t')
                            f.write(metabolite['refmet_name'] + '\n')

In [45]:
!del ST_metabolites_all.tsv